AllCops:
  Exclude:
    - 'spec/**/*'
    - 'lib/work_md/commands/**/*'
    - 'work_md.gemspec'

Layout/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: 20

