AllCops:
  Exclude:
    - 'spec/**/*'
    - 'lib/work/md/commands/**/*'
    - 'work-md.gemspec'

Layout/LineLength:
  Max: 90

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: 20

