# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in work-md.gemspec
gemspec

group :test, :development do
  gem 'byebug'
  gem 'fakefs', require: 'fakefs/safe'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.0'
  gem 'rubocop', '~> 0.80'
  gem 'rubocop-ast', '~> 1.4.0'
end
